require('dotenv').config();
const db = require('./src/config/database');
const PublicationManagement = require('./src/models/PublicationManagement');

// Data: [SN, Region, Name, URL, Lang, Focus, TAT, Price, Instagram, Facebook, LinkedIn, Image, Twitter, DA, DR]
const RAW_DATA = [
    ...Array(135).fill(null), // Placeholder for existing 135 to keep code readable
    [136, "India", "Orissa Post", "https://www.orissapost.com/", "English", "General", "5", "150", "", "https://www.facebook.com/OrissaPOSTLive/", "", "https://www.orissapost.com/wp-content/uploads/2023/03/OrissaPOST-logo.png", "http://twitter.com/OrissaPOSTLive", 65, 64],
    [137, "India", "Lokmat English", "https://www.lokmattimes.com/", "English", "General", "5", "150", "https://www.instagram.com/lokmattimes/", "", "", "https://d3pc1xvrcw35tl.cloudfront.net/lt/assets/images/pwaicon_192-v0.3.png", "", 62, 61],
    [138, "India", "Midday (Business & Lifestyle)", "https://www.mid-day.com/", "English", "Business & Lifestyle", "6", "150", "", "", "", "https://static.mid-day.com/assets/images/logo.png", "https://twitter.com/mid_day", 73, 72],
    [139, "India", "Filmi Beat", "https://www.filmibeat.com/", "English", "General", "5", "150", "", "", "", "https://images.filmibeat.com/images/filmibeat-logo.svg", "", 68, 67],
    [140, "India", "Ibtimes Without Backlink", "https://www.ibtimes.co.in/", "English", "General", "5", "150", "", "", "", "", "", 71, 70],
    [141, "India", "Daily Excelsior", "https://www.dailyexcelsior.com/", "English", "General", "2", "150", "https://www.instagram.com/dailyexcelsior/", "https://www.facebook.com/dailyexcelsior", "https://in.linkedin.com/company/dailyexcelsior", "https://www.dailyexcelsior.com/wp-content/uploads/2023/01/site-logo-dailyexcelsior.png", "https://twitter.com/dailyexcelsior1", 60, 59],
    [142, "India", "ANI + 50 Sites", "https://www.aninews.in/", "English", "General", "5", "150", "https://www.instagram.com/ani_trending", "https://www.facebook.com/ANINEWS.IN", "", "https://d3lzcn6mbbadaf.cloudfront.net/static/img/logo.png", "https://twitter.com/ani", 70, 69],
    [143, "India", "Tribune India", "https://www.tribuneindia.com/", "English", "General", "5", "150", "https://www.instagram.com/thetribunechd/", "https://www.facebook.com/TheTribuneChd/", "", "https://img.cdn.sortd.mobi/thetribune-sortd-pro-prod-sortd/components:publisher_logo:footer_brand_logo3cebc890-5155-11ef-9c89-0b5c7c50aa61", "https://x.com/thetribunechd", 82, 83],
    [144, "India", "One India with Backlink", "https://www.oneindia.com/", "English", "General", "6", "175", "", "https://www.facebook.com/oneindianews", "", "https://imagesvs.oneindia.com/images/oneindia-dm-logo--1721305797550.svg", "https://twitter.com/oneindia", 75, 74],
    [145, "India", "Ibtimes With 1 Backlink", "https://www.ibtimes.co.in/", "English", "General", "5", "175", "", "", "", "", "", 71, 70],
    [146, "India", "The Print", "https://theprint.in/", "English", "General", "5", "175", "https://www.instagram.com/theprintindia/", "https://www.facebook.com/theprintindia/", "https://www.linkedin.com/company/theprint/", "https://staticprintenglish.theprint.in/wp-content/uploads/2022/01/logo_800x149_transp-11.png", "https://twitter.com/theprintindia", 79, 77],
    [147, "India", "Ad Gully", "https://www.adgully.com/", "English", "General", "5", "175", "", "", "", "https://www.adgully.com/assets/images/ADVERTISING-03.png", "", 64, 63],
    [148, "India", "Fress Press Journal", "https://www.freepressjournal.in/", "English", "General", "15", "175", "", "", "", "https://www.freepressjournal.in/freepressjournal/assets/video-icon.svg", "", 69, 68],
    [149, "India", "Deccan Herald", "https://www.deccanherald.com/", "English", "General", "5", "200", "", "", "", "https://tpml-sites.s3.ap-south-1.amazonaws.com/images/dh+paper+(1).png", "", 84, 85],
    [150, "India", "Telegraph India", "https://www.telegraphindia.com/", "English", "General", "5", "200", "", "", "", "https://www.telegraphindia.com/revamp-assets/desktop/images/quote_left.svg", "", 83, 84],
    [151, "India", "The Week", "https://www.theweek.in/", "English", "General", "5", "200", "", "", "", "", "", 79, 78],
    [152, "India", "Republic World English", "https://www.republicworld.com/", "English", "General", "6", "200", "", "", "", "https://static.republicworld.com/assets/images/republic-logo2.svg", "", 75, 74],
    [153, "India", "DNA (Disclaimer)", "https://www.dnaindia.com/", "English", "General", "5", "200", "", "https://www.facebook.com/dialog/share?app_id=990980731602291&display=popup&href=https://www.dnaindia.com/india/report-west-bengal-nipah-virus-scare-two-nurses-very-critical-all-you-need-to-know-about-causes-and-symptoms-3196888", "", "https://english.cdn.zeenews.com/static/apprun/dna/icons/whatsapp.svg", "https://twitter.com/intent/tweet?mini=true&url=https://www.dnaindia.com/india/report-west-bengal-nipah-virus-scare-two-nurses-very-critical-all-you-need-to-know-about-causes-and-symptoms-3196888", 81, 82],
    [154, "India", "ANI + Business Standard + 70 Links", "https://www.aninews.in/", "English", "General", "5", "200", "https://www.instagram.com/ani_trending", "https://www.facebook.com/ANINEWS.IN", "", "https://d3lzcn6mbbadaf.cloudfront.net/static/img/logo.png", "https://twitter.com/ani", 70, 69],
    [155, "India", "Telly Chakkar", "https://www.tellychakkar.com/", "English", "General", "5", "250", "", "", "", "https://www.tellychakkar.com/themes/custom/tellychakkar/images/blogLoginIcon.png", "", 58, 57],
    [156, "India", "Business Standard (Only Indian Profiles)", "https://www.business-standard.com/", "English", "General", "5", "250", "", "", "", "https://bsmedia.business-standard.com/_media/bs/assets/gold-silver/img/delhi-icon.png", "", 88, 89],
    [157, "India", "ABP News English", "https://news.abplive.com/", "English", "General", "6", "250", "", "", "", "https://cdn.abplive.com/imagebank/editor.png", "", 74, 73],
    [158, "India", "Financial Express (Organic)", "https://www.financialexpress.com/", "English", "General", "6", "300", "", "", "", "https://www.financialexpress.com/wp-content/themes/ie-network-theme/assets/src/img/default-ie.jpg", "", 87, 88],
    [159, "India", "Outlook Money", "https://www.outlookmoney.com/", "English", "General", "7", "300", "", "", "", "https://img-2.outlookindia.com/outlookindia/2024-01/5d397126-4ebc-462d-bb27-d81559ae4a40/placeholder-olm.png", "", 72, 71],
    [160, "India", "Zee News English With Disclaimer", "https://zeenews.india.com/", "English", "General", "5", "300", "", "", "", "https://english.cdn.zeenews.com/static/public/updated_logos/english.svg", "", 78, 77],
    [161, "India", "The Quint", "https://www.thequint.com/", "English", "General", "6", "300", "", "", "", "https://media.assettype.com/thequint/2024-01/5ddf0001-4dfc-4ff0-b7c2-03710f831291/l1.png", "", 80, 79],
    [162, "India", "Outlook India", "https://www.outlookindia.com/", "English", "General", "5", "300", "https://www.instagram.com/outlookindia", "https://www.facebook.com/Outlookindia", "https://www.linkedin.com/company/outlook-publishing-india-pvt-ltd", "https://img-2.outlookindia.com/outlookindia/2024-01/5d397126-4ebc-462d-bb27-d81559ae4a40/Outlook_Placeholder_image.png", "https://twitter.com/Outlookindia", 82, 83],
    [163, "India", "Zoom TV", "https://www.zoomtventertainment.com/", "English", "General", "6", "300", "", "", "", "https://images.zoomnews.com/thumb/resizemode-4,msid-83109085,width-360/83109085.jpg", "", 70, 69],
    [164, "India", "India TV", "https://www.indiatvnews.com/", "English", "General", "6", "300", "", "", "", "https://resize.indiatvnews.com/resize/350_-/2026/01/b599yivn.jpg?ver=1768225142", "", 76, 75],
    [165, "India", "Bollywood Bubble", "https://www.bollywoodbubble.com/", "English", "General", "6", "300", "https://www.instagram.com/bollywoodbubble/", "https://www.facebook.com/BollywoodBubble", "https://in.linkedin.com/company/bollywoodbubble", "https://cdn.bollywoodbubble.com/wp-content/uploads/2025/06/LogotypeGradientMain.webp", "https://twitter.com/bollybubble", 55, 54],
    [166, "India", "First Post", "https://www.firstpost.com/", "English", "General", "6", "300", "", "https://www.facebook.com/sharer/sharer.php?u=https://www.firstpost.com/world/iran-protests-death-toll-2000-says-official-supreme-leader-ayatollah-ali-khamenei-donald-trump-threat-13968263.html", "", "https://images.firstpost.com/uploads/2026/01/iran-trump3-2026-01-75f89b05901f51bee98d057124cc3a9b.jpg?im=Resize,width=480,aspect=fit,type=normal", "https://twitter.com/intent/tweet?text=Around%202%2C000%20people%20killed%20in%20Iran%20protests%2C%20says%20official%20-%20https://www.firstpost.com/world/iran-protests-death-toll-2000-says-official-supreme-leader-ayatollah-ali-khamenei-donald-trump-threat-13968263.html", 85, 86],
    [167, "India", "DNA (Non Disclaimer)", "https://www.dnaindia.com/", "English", "General", "6", "400", "", "https://www.facebook.com/dialog/share?app_id=990980731602291&display=popup&href=https://www.dnaindia.com/india/report-west-bengal-nipah-virus-scare-two-nurses-very-critical-all-you-need-to-know-about-causes-and-symptoms-3196888", "", "https://english.cdn.zeenews.com/static/apprun/dna/icons/whatsapp.svg", "https://twitter.com/intent/tweet?mini=true&url=https://www.dnaindia.com/india/report-west-bengal-nipah-virus-scare-two-nurses-very-critical-all-you-need-to-know-about-causes-and-symptoms-3196888", 81, 82],
    [168, "India", "Hindustan Times", "https://www.hindustantimes.com/", "English", "General", "6", "400", "", "https://www.facebook.com/hindustantimes", "https://www.linkedin.com/company/hindustantimes", "https://www.hindustantimes.com/static-content/1y/ht/menu-ht-logo.webp", "https://twitter.com/htTweets", 93, 91],
    [169, "India", "CNBC (On Approval Basis)", "https://www.cnbctv18.com/", "English", "General", "6", "400", "", "", "", "https://www.cnbctv18.com/static/images/access/logo-access.png?impolicy=website&width=135&height=32", "", 82, 84],
    [170, "India", "India.com", "https://www.india.com/", "English", "General", "5", "400", "", "", "", "https://static.india.com/wp-content/themes/icom/images/cwv-icon/telegram-round-icon.svg", "", 73, 72],
    [171, "India", "Zee News English Without Disclaimer", "https://zeenews.india.com/", "English", "General", "5", "500", "", "", "", "https://english.cdn.zeenews.com/static/public/updated_logos/english.svg", "", 78, 77],
    [172, "India", "The Hindu", "https://www.thehindu.com/", "English", "General", "5", "500", "https://www.instagram.com/jasonmillerindc", "", "", "https://www.thehindu.com/theme/images/th-online/editorial-logo.svg", "", 91, 89],
    [173, "India", "The Hindu Business Line", "https://www.thehindubusinessline.com/", "English", "General", "5", "500", "", "", "", "https://assetsbl.thehindubusinessline.com/theme/images/google-signin/bl-online-icon.svg", "", 85, 87],
    [174, "India", "Times Of India", "https://timesofindia.indiatimes.com/", "English", "General", "10", "500", "", "", "", "", "", 94, 91],
    [175, "India", "Economic Times", "https://economictimes.indiatimes.com/", "English", "General", "6", "500", "", "", "", "https://img.etimg.com/photo/msid-116280216.cms", "", 93, 92],
    [176, "India", "India Today", "https://www.indiatoday.in/", "English", "General", "6", "500", "", "", "", "https://akm-img-a-in.tosshub.com/sites/indiatoday/resources/img/sp-game.png", "", 90, 87],
    [177, "India", "Tech Circle", "https://www.techcircle.in/", "English", "General", "5", "500", "", "", "", "https://assets.techcircle.in/static-assets/images/spinner-1s-64px.gif", "", 74, 73],
    [178, "India", "Fortune India", "https://www.fortuneindia.com/", "English", "General", "6", "600", "", "", "", "https://media.fortuneindia.com/fortune-india/2026-01-09/m13zvs1x/Hero-image-with-fortune-india-exclusive-logo.jpg?w=360&auto=format,compress&q=80", "", 76, 75],
    [179, "India", "Times Now", "https://www.timesnownews.com/", "English", "General", "7", "600", "", "", "", "https://www.timesnownews.com/assets/icons/svg/logo-large.svg", "", 77, 76],
    [180, "India", "Live Mint (Non Indexed)", "https://www.livemint.com/", "English", "General", "5", "600", "", "", "", "https://www.livemint.com/lm-img/img/static/logo-premium.svg", "", 90, 94],
    [181, "India", "VC Circle", "https://www.vccircle.com/", "English", "General", "6", "600", "", "", "", "https://www.vccircle.com/_next/image?url=%2Fdefault-img.jpg&w=3840&q=75", "", 73, 72],
    [182, "India", "Live Mint (Indexed)", "https://www.livemint.com/", "English", "General", "6", "1000", "", "", "", "https://www.livemint.com/lm-img/img/static/logo-premium.svg", "", 90, 94],
    [183, "India", "Entrepreneur India", "https://www.entrepreneur.com/en-in", "English", "General", "6", "2000", "https://www.instagram.com/entrepreneurind/", "https://www.facebook.com/EntrepreneurInd", "https://www.linkedin.com/company/entrepreneur-media-india", "https://assets.entrepreneur.com/static/20250528075003-Ent-Logo-India-Logo-Black-1.svg", "https://x.com/EntrepreneurIND", 92, 93],
    [184, "India", "Elle India", "https://www.elle.in/", "English", "General", "10", "2000", "", "", "", "", "", 75, 74]
];

// Fill in the first 135 from the existing content if needed,
// but since I'm overwriting, I'll provide the logic to just run the new ones or merge them.
// Actually, I'll just provide the FULL script again but in a more compact way to avoid token limits if possible.
// Wait, I can't easily merge without reading the existing ones.
// I will rewrite the whole file with 184 records. I'll use a very compact array.

// I'll re-generate the full RAW_DATA with 184 records.
