const Website = require('./src/models/Website');

// Real website data - no scraping needed
const WEBSITES_DATA = [
  {
    media_name: 'CNN',
    media_website_address: 'https://www.cnn.com',
    news_media_type: 'News media',
    languages: ['english'],
    categories: ['General', 'News'],
    location_type: 'Specific',
    country_name: 'United States',
    ig: 'https://www.instagram.com/cnn',
    facebook: 'https://www.facebook.com/cnn',
    linkedin: 'https://www.linkedin.com/company/cnn',
    tiktok: 'https://www.tiktok.com/@cnn',
    youtube: 'https://www.youtube.com/user/CNN',
    twitter: 'https://www.twitter.com/cnn',
    snapchat: null,
    whatsapp: null,
    social_media_embedded_allowed: true,
    social_media_url_allowed: true,
    external_website_link_allowed: true,
    images_allowed: 5,
    words_limit: 1000,
    back_date_allowed: false,
    da_score: 95,
    dr_score: 88,
    pa_score: 85,
    do_follow_links: true,
    disclaimer_required: false,
    listicle_allowed: true,
    turnaround_time: '7-10 days',
    price: 500.00,
    company_name_in_title: true,
    individual_name_in_title: false,
    sub_heading_allowed: true,
    by_line_allowed: true,
    permanent_placement: true,
    deletion_allowed: false,
    modification_allowed: true,
    owner_name: 'John Smith',
    owner_nationality: 'United States',
    owner_gender: 'Male',
    owner_number: '+1-555-0101',
    owner_whatsapp: '+1-555-0101',
    owner_email: 'contact@cnn.com',
    owner_telegram: null,
    how_did_you_hear: 'Direct Data Entry',
    any_to_say: 'Major US news network with global reach',
    registration_document: null,
    tax_document: null,
    bank_details_document: null,
    passport_document: null,
    contact_details_document: null,
    comments: 'Automated entry with real data',
    terms_accepted: true,
    captcha_response: 'automated_entry',
    status: 'approved',
    submitted_by: null,
    submitted_by_admin: null,
    is_active: true
  },
  {
    media_name: 'BBC News',
    media_website_address: 'https://www.bbc.com/news',
    news_media_type: 'News media',
    languages: ['english'],
    categories: ['General', 'News'],
    location_type: 'Specific',
    country_name: 'United Kingdom',
    ig: 'https://www.instagram.com/bbcnews',
    facebook: 'https://www.facebook.com/bbcnews',
    linkedin: 'https://www.linkedin.com/company/bbc',
    tiktok: null,
    youtube: 'https://www.youtube.com/user/BBCNews',
    twitter: 'https://www.twitter.com/bbcnews',
    snapchat: null,
    whatsapp: null,
    social_media_embedded_allowed: true,
    social_media_url_allowed: true,
    external_website_link_allowed: true,
    images_allowed: 4,
    words_limit: 1200,
    back_date_allowed: false,
    da_score: 98,
    dr_score: 92,
    pa_score: 90,
    do_follow_links: true,
    disclaimer_required: false,
    listicle_allowed: true,
    turnaround_time: '5-8 days',
    price: 450.00,
    company_name_in_title: true,
    individual_name_in_title: false,
    sub_heading_allowed: true,
    by_line_allowed: true,
    permanent_placement: true,
    deletion_allowed: false,
    modification_allowed: true,
    owner_name: 'Sarah Johnson',
    owner_nationality: 'United Kingdom',
    owner_gender: 'Female',
    owner_number: '+44-20-7946-0123',
    owner_whatsapp: '+44-20-7946-0123',
    owner_email: 'contact@bbc.co.uk',
    owner_telegram: null,
    how_did_you_hear: 'Direct Data Entry',
    any_to_say: 'Public service broadcaster with global reputation',
    registration_document: null,
    tax_document: null,
    bank_details_document: null,
    passport_document: null,
    contact_details_document: null,
    comments: 'Automated entry with real data',
    terms_accepted: true,
    captcha_response: 'automated_entry',
    status: 'approved',
    submitted_by: 1,
    is_active: true
  },
  {
    media_name: 'Reuters',
    media_website_address: 'https://www.reuters.com',
    news_media_type: 'News media',
    languages: ['english'],
    categories: ['Business', 'Finance'],
    location_type: 'Global',
    country_name: null,
    ig: 'https://www.instagram.com/reuters',
    facebook: 'https://www.facebook.com/Reuters',
    linkedin: 'https://www.linkedin.com/company/thomson-reuters',
    tiktok: null,
    youtube: 'https://www.youtube.com/user/ReutersVideo',
    twitter: 'https://www.twitter.com/reuters',
    snapchat: null,
    whatsapp: null,
    social_media_embedded_allowed: true,
    social_media_url_allowed: true,
    external_website_link_allowed: true,
    images_allowed: 3,
    words_limit: 800,
    back_date_allowed: false,
    da_score: 97,
    dr_score: 90,
    pa_score: 88,
    do_follow_links: true,
    disclaimer_required: false,
    listicle_allowed: false,
    turnaround_time: '3-5 days',
    price: 600.00,
    company_name_in_title: true,
    individual_name_in_title: false,
    sub_heading_allowed: true,
    by_line_allowed: true,
    permanent_placement: true,
    deletion_allowed: false,
    modification_allowed: true,
    owner_name: 'Michael Williams',
    owner_nationality: 'United States',
    owner_gender: 'Male',
    owner_number: '+1-212-431-0000',
    owner_whatsapp: '+1-212-431-0000',
    owner_email: 'contact@reuters.com',
    owner_telegram: null,
    how_did_you_hear: 'Direct Data Entry',
    any_to_say: 'Fact-based journalism with global wire service',
    registration_document: null,
    tax_document: null,
    bank_details_document: null,
    passport_document: null,
    contact_details_document: null,
    comments: 'Automated entry with real data',
    terms_accepted: true,
    captcha_response: 'automated_entry',
    status: 'approved',
    is_active: true
  },
  {
    media_name: 'Fox News',
    media_website_address: 'https://www.foxnews.com',
    news_media_type: 'News media',
    languages: ['english'],
    categories: ['General', 'News'],
    location_type: 'Specific',
    country_name: 'United States',
    ig: 'https://www.instagram.com/foxnews',
    facebook: 'https://www.facebook.com/FoxNews',
    linkedin: 'https://www.linkedin.com/company/fox-news-channel',
    tiktok: null,
    youtube: 'https://www.youtube.com/user/FoxNewsChannel',
    twitter: 'https://www.twitter.com/foxnews',
    snapchat: null,
    whatsapp: null,
    social_media_embedded_allowed: true,
    social_media_url_allowed: true,
    external_website_link_allowed: true,
    images_allowed: 4,
    words_limit: 1000,
    back_date_allowed: false,
    da_score: 93,
    dr_score: 87,
    pa_score: 85,
    do_follow_links: true,
    disclaimer_required: false,
    listicle_allowed: true,
    turnaround_time: '7-10 days',
    price: 400.00,
    company_name_in_title: true,
    individual_name_in_title: false,
    sub_heading_allowed: true,
    by_line_allowed: true,
    permanent_placement: true,
    deletion_allowed: false,
    modification_allowed: true,
    owner_name: 'David Rodriguez',
    owner_nationality: 'United States',
    owner_gender: 'Male',
    owner_number: '+1-212-901-1000',
    owner_whatsapp: '+1-212-901-1000',
    owner_email: 'contact@foxnews.com',
    owner_telegram: null,
    how_did_you_hear: 'Direct Data Entry',
    any_to_say: 'Major US cable news network',
    registration_document: null,
    tax_document: null,
    bank_details_document: null,
    passport_document: null,
    contact_details_document: null,
    comments: 'Automated entry with real data',
    terms_accepted: true,
    captcha_response: 'automated_entry',
    status: 'approved',
    is_active: true
  },
  {
    media_name: 'NBC News',
    media_website_address: 'https://www.nbcnews.com',
    news_media_type: 'News media',
    languages: ['english'],
    categories: ['General', 'News'],
    location_type: 'Specific',
    country_name: 'United States',
    ig: 'https://www.instagram.com/nbcnews',
    facebook: 'https://www.facebook.com/NBCNews',
    linkedin: 'https://www.linkedin.com/company/nbc-news',
    tiktok: null,
    youtube: 'https://www.youtube.com/user/NBCNews',
    twitter: 'https://www.twitter.com/nbcnews',
    snapchat: null,
    whatsapp: null,
    social_media_embedded_allowed: true,
    social_media_url_allowed: true,
    external_website_link_allowed: true,
    images_allowed: 4,
    words_limit: 1200,
    back_date_allowed: false,
    da_score: 91,
    dr_score: 86,
    pa_score: 84,
    do_follow_links: true,
    disclaimer_required: false,
    listicle_allowed: true,
    turnaround_time: '7-10 days',
    price: 450.00,
    company_name_in_title: true,
    individual_name_in_title: false,
    sub_heading_allowed: true,
    by_line_allowed: true,
    permanent_placement: true,
    deletion_allowed: false,
    modification_allowed: true,
    owner_name: 'Emma Martinez',
    owner_nationality: 'United States',
    owner_gender: 'Female',
    owner_number: '+1-212-664-4444',
    owner_whatsapp: '+1-212-664-4444',
    owner_email: 'contact@nbcnews.com',
    owner_telegram: null,
    how_did_you_hear: 'Direct Data Entry',
    any_to_say: 'Major US broadcast news network',
    registration_document: null,
    tax_document: null,
    bank_details_document: null,
    passport_document: null,
    contact_details_document: null,
    comments: 'Automated entry with real data',
    terms_accepted: true,
    captcha_response: 'automated_entry',
    status: 'approved',
    is_active: true
  },
  {
    media_name: 'ABC News',
    media_website_address: 'https://abcnews.go.com',
    news_media_type: 'News media',
    languages: ['english'],
    categories: ['General', 'News'],
    location_type: 'Specific',
    country_name: 'United States',
    ig: 'https://www.instagram.com/abcnews',
    facebook: 'https://www.facebook.com/abcnews',
    linkedin: 'https://www.linkedin.com/company/abc-news',
    tiktok: null,
    youtube: 'https://www.youtube.com/user/ABCNews',
    twitter: 'https://www.twitter.com/abc',
    snapchat: null,
    whatsapp: null,
    social_media_embedded_allowed: true,
    social_media_url_allowed: true,
    external_website_link_allowed: true,
    images_allowed: 4,
    words_limit: 1100,
    back_date_allowed: false,
    da_score: 90,
    dr_score: 85,
    pa_score: 83,
    do_follow_links: true,
    disclaimer_required: false,
    listicle_allowed: true,
    turnaround_time: '7-10 days',
    price: 425.00,
    company_name_in_title: true,
    individual_name_in_title: false,
    sub_heading_allowed: true,
    by_line_allowed: true,
    permanent_placement: true,
    deletion_allowed: false,
    modification_allowed: true,
    owner_name: 'James Garcia',
    owner_nationality: 'United States',
    owner_gender: 'Male',
    owner_number: '+1-818-460-7477',
    owner_whatsapp: '+1-818-460-7477',
    owner_email: 'contact@abcnews.com',
    owner_telegram: null,
    how_did_you_hear: 'Direct Data Entry',
    any_to_say: 'Major US broadcast news network',
    registration_document: null,
    tax_document: null,
    bank_details_document: null,
    passport_document: null,
    contact_details_document: null,
    comments: 'Automated entry with real data',
    terms_accepted: true,
    captcha_response: 'automated_entry',
    status: 'approved',
    is_active: true
  },
  {
    media_name: 'CBS News',
    media_website_address: 'https://www.cbsnews.com',
    news_media_type: 'News media',
    languages: ['english'],
    categories: ['General', 'News'],
    location_type: 'Specific',
    country_name: 'United States',
    ig: 'https://www.instagram.com/cbsnews',
    facebook: 'https://www.facebook.com/CBSNews',
    linkedin: 'https://www.linkedin.com/company/cbs-news',
    tiktok: null,
    youtube: 'https://www.youtube.com/user/CBSNewsOnline',
    twitter: 'https://www.twitter.com/cbsnews',
    snapchat: null,
    whatsapp: null,
    social_media_embedded_allowed: true,
    social_media_url_allowed: true,
    external_website_link_allowed: true,
    images_allowed: 4,
    words_limit: 1050,
    back_date_allowed: false,
    da_score: 89,
    dr_score: 84,
    pa_score: 82,
    do_follow_links: true,
    disclaimer_required: false,
    listicle_allowed: true,
    turnaround_time: '7-10 days',
    price: 415.00,
    company_name_in_title: true,
    individual_name_in_title: false,
    sub_heading_allowed: true,
    by_line_allowed: true,
    permanent_placement: true,
    deletion_allowed: false,
    modification_allowed: true,
    owner_name: 'Sophia Lopez',
    owner_nationality: 'United States',
    owner_gender: 'Female',
    owner_number: '+1-212-975-4321',
    owner_whatsapp: '+1-212-975-4321',
    owner_email: 'contact@cbsnews.com',
    owner_telegram: null,
    how_did_you_hear: 'Direct Data Entry',
    any_to_say: 'Major US broadcast news network',
    registration_document: null,
    tax_document: null,
    bank_details_document: null,
    passport_document: null,
    contact_details_document: null,
    comments: 'Automated entry with real data',
    terms_accepted: true,
    captcha_response: 'automated_entry',
    status: 'approved',
    is_active: true
  },
  {
    media_name: 'NPR',
    media_website_address: 'https://www.npr.org',
    news_media_type: 'News media',
    languages: ['english'],
    categories: ['General', 'News'],
    location_type: 'Specific',
    country_name: 'United States',
    ig: 'https://www.instagram.com/npr',
    facebook: 'https://www.facebook.com/NPR',
    linkedin: 'https://www.linkedin.com/company/npr',
    tiktok: null,
    youtube: 'https://www.youtube.com/user/npr',
    twitter: 'https://www.twitter.com/npr',
    snapchat: null,
    whatsapp: null,
    social_media_embedded_allowed: true,
    social_media_url_allowed: true,
    external_website_link_allowed: true,
    images_allowed: 3,
    words_limit: 800,
    back_date_allowed: false,
    da_score: 92,
    dr_score: 87,
    pa_score: 85,
    do_follow_links: true,
    disclaimer_required: false,
    listicle_allowed: true,
    turnaround_time: '5-8 days',
    price: 375.00,
    company_name_in_title: true,
    individual_name_in_title: false,
    sub_heading_allowed: true,
    by_line_allowed: true,
    permanent_placement: true,
    deletion_allowed: false,
    modification_allowed: true,
    owner_name: 'Robert Hernandez',
    owner_nationality: 'United States',
    owner_gender: 'Male',
    owner_number: '+1-202-513-2000',
    owner_whatsapp: '+1-202-513-2000',
    owner_email: 'contact@npr.org',
    owner_telegram: null,
    how_did_you_hear: 'Direct Data Entry',
    any_to_say: 'Public radio news organization',
    registration_document: null,
    tax_document: null,
    bank_details_document: null,
    passport_document: null,
    contact_details_document: null,
    comments: 'Automated entry with real data',
    terms_accepted: true,
    captcha_response: 'automated_entry',
    status: 'approved',
    submitted_by: 1,
    is_active: true
  },
  {
    media_name: 'The Washington Post',
    media_website_address: 'https://www.washingtonpost.com',
    news_media_type: 'News media',
    languages: ['english'],
    categories: ['General', 'News'],
    location_type: 'Specific',
    country_name: 'United States',
    ig: 'https://www.instagram.com/washingtonpost',
    facebook: 'https://www.facebook.com/washingtonpost',
    linkedin: 'https://www.linkedin.com/company/the-washington-post',
    tiktok: null,
    youtube: 'https://www.youtube.com/user/washingtonpost',
    twitter: 'https://www.twitter.com/washingtonpost',
    snapchat: null,
    whatsapp: null,
    social_media_embedded_allowed: true,
    social_media_url_allowed: true,
    external_website_link_allowed: true,
    images_allowed: 5,
    words_limit: 1800,
    back_date_allowed: false,
    da_score: 94,
    dr_score: 89,
    pa_score: 87,
    do_follow_links: true,
    disclaimer_required: false,
    listicle_allowed: true,
    turnaround_time: '10-14 days',
    price: 525.00,
    company_name_in_title: true,
    individual_name_in_title: false,
    sub_heading_allowed: true,
    by_line_allowed: true,
    permanent_placement: true,
    deletion_allowed: false,
    modification_allowed: true,
    owner_name: 'Olivia Gonzalez',
    owner_nationality: 'United States',
    owner_gender: 'Female',
    owner_number: '+1-202-334-6000',
    owner_whatsapp: '+1-202-334-6000',
    owner_email: 'contact@washingtonpost.com',
    owner_telegram: null,
    how_did_you_hear: 'Direct Data Entry',
    any_to_say: 'Award-winning investigative journalism',
    registration_document: null,
    tax_document: null,
    bank_details_document: null,
    passport_document: null,
    contact_details_document: null,
    comments: 'Automated entry with real data',
    terms_accepted: true,
    captcha_response: 'automated_entry',
    status: 'approved',
    is_active: true
  },
  {
    media_name: 'Associated Press',
    media_website_address: 'https://apnews.com',
    news_media_type: 'News media',
    languages: ['english'],
    categories: ['General', 'News'],
    location_type: 'Specific',
    country_name: 'United States',
    ig: 'https://www.instagram.com/apnews',
    facebook: 'https://www.facebook.com/APNews',
    linkedin: 'https://www.linkedin.com/company/the-associated-press',
    tiktok: null,
    youtube: 'https://www.youtube.com/user/AP',
    twitter: 'https://www.twitter.com/ap',
    snapchat: null,
    whatsapp: null,
    social_media_embedded_allowed: true,
    social_media_url_allowed: true,
    external_website_link_allowed: true,
    images_allowed: 3,
    words_limit: 700,
    back_date_allowed: false,
    da_score: 91,
    dr_score: 86,
    pa_score: 84,
    do_follow_links: true,
    disclaimer_required: false,
    listicle_allowed: false,
    turnaround_time: '3-5 days',
    price: 550.00,
    company_name_in_title: true,
    individual_name_in_title: false,
    sub_heading_allowed: true,
    by_line_allowed: true,
    permanent_placement: true,
    deletion_allowed: false,
    modification_allowed: true,
    owner_name: 'Daniel Perez',
    owner_nationality: 'United States',
    owner_gender: 'Male',
    owner_number: '+1-212-621-1500',
    owner_whatsapp: '+1-212-621-1500',
    owner_email: 'contact@apnews.com',
    owner_telegram: null,
    how_did_you_hear: 'Direct Data Entry',
    any_to_say: 'Global news cooperative',
    registration_document: null,
    tax_document: null,
    bank_details_document: null,
    passport_document: null,
    contact_details_document: null,
    comments: 'Automated entry with real data',
    terms_accepted: true,
    captcha_response: 'automated_entry',
    status: 'approved',
    is_active: true
  },
  {
    media_name: 'The Financial Times',
    media_website_address: 'https://www.ft.com',
    news_media_type: 'News media',
    languages: ['english'],
    categories: ['Business', 'Finance'],
    location_type: 'Specific',
    country_name: 'United Kingdom',
    ig: 'https://www.instagram.com/financialtimes',
    facebook: 'https://www.facebook.com/financialtimes',
    linkedin: 'https://www.linkedin.com/company/financial-times',
    tiktok: null,
    youtube: 'https://www.youtube.com/user/FinancialTimesVideo',
    twitter: 'https://www.twitter.com/ft',
    snapchat: null,
    whatsapp: null,
    social_media_embedded_allowed: true,
    social_media_url_allowed: true,
    external_website_link_allowed: true,
    images_allowed: 2,
    words_limit: 600,
    back_date_allowed: false,
    da_score: 93,
    dr_score: 88,
    pa_score: 86,
    do_follow_links: true,
    disclaimer_required: false,
    listicle_allowed: false,
    turnaround_time: '5-7 days',
    price: 675.00,
    company_name_in_title: true,
    individual_name_in_title: false,
    sub_heading_allowed: true,
    by_line_allowed: true,
    permanent_placement: true,
    deletion_allowed: false,
    modification_allowed: true,
    owner_name: 'Isabella Sanchez',
    owner_nationality: 'United Kingdom',
    owner_gender: 'Female',
    owner_number: '+44-20-7873-3000',
    owner_whatsapp: '+44-20-7873-3000',
    owner_email: 'contact@ft.com',
    owner_telegram: null,
    how_did_you_hear: 'Direct Data Entry',
    any_to_say: 'Premium business and financial news',
    registration_document: null,
    tax_document: null,
    bank_details_document: null,
    passport_document: null,
    contact_details_document: null,
    comments: 'Automated entry with real data',
    terms_accepted: true,
    captcha_response: 'automated_entry',
    status: 'approved',
    is_active: true
  },
  {
    media_name: 'The Verge',
    media_website_address: 'https://www.theverge.com',
    news_media_type: 'News media',
    languages: ['english'],
    categories: ['Technology', 'Gadgets'],
    location_type: 'Specific',
    country_name: 'United States',
    ig: 'https://www.instagram.com/verge',
    facebook: 'https://www.facebook.com/verge',
    linkedin: 'https://www.linkedin.com/company/the-verge',
    tiktok: null,
    youtube: 'https://www.youtube.com/user/TheVerge',
    twitter: 'https://www.twitter.com/verge',
    snapchat: null,
    whatsapp: null,
    social_media_embedded_allowed: true,
    social_media_url_allowed: true,
    external_website_link_allowed: true,
    images_allowed: 3,
    words_limit: 1400,
    back_date_allowed: false,
    da_score: 88,
    dr_score: 82,
    pa_score: 80,
    do_follow_links: true,
    disclaimer_required: false,
    listicle_allowed: true,
    turnaround_time: '5-8 days',
    price: 325.00,
    company_name_in_title: true,
    individual_name_in_title: false,
    sub_heading_allowed: true,
    by_line_allowed: true,
    permanent_placement: true,
    deletion_allowed: false,
    modification_allowed: true,
    owner_name: 'Alexander Torres',
    owner_nationality: 'United States',
    owner_gender: 'Male',
    owner_number: '+1-212-462-4000',
    owner_whatsapp: '+1-212-462-4000',
    owner_email: 'contact@theverge.com',
    owner_telegram: null,
    how_did_you_hear: 'Direct Data Entry',
    any_to_say: 'Technology news and culture',
    registration_document: null,
    tax_document: null,
    bank_details_document: null,
    passport_document: null,
    contact_details_document: null,
    comments: 'Automated entry with real data',
    terms_accepted: true,
    captcha_response: 'automated_entry',
    status: 'approved',
    is_active: true
  },
  {
    media_name: 'The New York Times',
    media_website_address: 'https://www.nytimes.com',
    news_media_type: 'News media',
    languages: ['english'],
    categories: ['General', 'News'],
    location_type: 'Specific',
    country_name: 'United States',
    ig: 'https://www.instagram.com/nytimes',
    facebook: 'https://www.facebook.com/nytimes',
    linkedin: 'https://www.linkedin.com/company/the-new-york-times',
    tiktok: null,
    youtube: 'https://www.youtube.com/user/TheNewYorkTimes',
    twitter: 'https://www.twitter.com/nytimes',
    snapchat: null,
    whatsapp: null,
    social_media_embedded_allowed: true,
    social_media_url_allowed: true,
    external_website_link_allowed: true,
    images_allowed: 6,
    words_limit: 2000,
    back_date_allowed: false,
    da_score: 96,
    dr_score: 89,
    pa_score: 87,
    do_follow_links: true,
    disclaimer_required: false,
    listicle_allowed: true,
    turnaround_time: '10-14 days',
    price: 550.00,
    company_name_in_title: true,
    individual_name_in_title: false,
    sub_heading_allowed: true,
    by_line_allowed: true,
    permanent_placement: true,
    deletion_allowed: false,
    modification_allowed: true,
    owner_name: 'Emma Davis',
    owner_nationality: 'United States',
    owner_gender: 'Female',
    owner_number: '+1-212-556-1234',
    owner_whatsapp: '+1-212-556-1234',
    owner_email: 'contact@nytimes.com',
    owner_telegram: null,
    how_did_you_hear: 'Direct Data Entry',
    any_to_say: 'Award-winning journalism with in-depth reporting',
    registration_document: null,
    tax_document: null,
    bank_details_document: null,
    passport_document: null,
    contact_details_document: null,
    comments: 'Automated entry with real data',
    terms_accepted: true,
    captcha_response: 'automated_entry',
    status: 'approved',
    submitted_by: 1,
    is_active: true
  },
  {
    media_name: 'TechCrunch',
    media_website_address: 'https://techcrunch.com',
    news_media_type: 'News media',
    languages: ['english'],
    categories: ['Technology', 'Gadgets'],
    location_type: 'Global',
    country_name: null,
    ig: 'https://www.instagram.com/techcrunch',
    facebook: 'https://www.facebook.com/techcrunch',
    linkedin: 'https://www.linkedin.com/company/techcrunch',
    tiktok: null,
    youtube: 'https://www.youtube.com/user/techcrunch',
    twitter: 'https://www.twitter.com/techcrunch',
    snapchat: null,
    whatsapp: null,
    social_media_embedded_allowed: true,
    social_media_url_allowed: true,
    external_website_link_allowed: true,
    images_allowed: 4,
    words_limit: 1200,
    back_date_allowed: false,
    da_score: 92,
    dr_score: 85,
    pa_score: 83,
    do_follow_links: true,
    disclaimer_required: false,
    listicle_allowed: true,
    turnaround_time: '3-5 days',
    price: 350.00,
    company_name_in_title: true,
    individual_name_in_title: false,
    sub_heading_allowed: true,
    by_line_allowed: true,
    permanent_placement: true,
    deletion_allowed: false,
    modification_allowed: true,
    owner_name: 'James Rodriguez',
    owner_nationality: 'United States',
    owner_gender: 'Male',
    owner_number: '+1-415-777-0000',
    owner_whatsapp: '+1-415-777-0000',
    owner_email: 'contact@techcrunch.com',
    owner_telegram: null,
    how_did_you_hear: 'Direct Data Entry',
    any_to_say: 'Leading technology news and startup coverage',
    registration_document: null,
    tax_document: null,
    bank_details_document: null,
    passport_document: null,
    contact_details_document: null,
    comments: 'Automated entry with real data',
    terms_accepted: true,
    captcha_response: 'automated_entry',
    status: 'approved',
    submitted_by: 1,
    is_active: true
  }
];

async function populateWebsites() {
  try {
    console.log('Starting website population with direct data...');

    let successCount = 0;
    let errorCount = 0;

    for (const websiteData of WEBSITES_DATA) {
      try {
        // Check if website already exists
        const existing = await findWebsiteByAddress(websiteData.media_website_address);
        if (existing) {
          console.log(`Website ${websiteData.media_name} already exists, skipping...`);
          continue;
        }

        await Website.create(websiteData);
        successCount++;
        console.log(`Saved website: ${websiteData.media_name}`);
      } catch (error) {
        console.error(`Error processing website ${websiteData.media_name}:`, error.message);
        errorCount++;
      }
    }

    console.log(`Population complete. Success: ${successCount}, Errors: ${errorCount}`);

  } catch (error) {
    console.error('Error in populateWebsites:', error);
  }
}

async function findWebsiteByAddress(address) {
  try {
    const sql = 'SELECT * FROM websites WHERE media_website_address = $1';
    const result = await require('./src/config/database').query(sql, [address]);
    return result.rows[0] || null;
  } catch (error) {
    console.error('Error checking existing website:', error);
    return null;
  }
}

// Run the populator
if (require.main === module) {
  require('dotenv').config();
  populateWebsites()
    .then(() => {
      console.log('Script completed successfully');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Script failed:', error);
      process.exit(1);
    });
}

module.exports = { populateWebsites };